const list = [
  {
    id: 1,
    vUrl: "http://qn.ifakq.com/t1.mp4",
    title: "Samson",
    desc: "公示！到2050年，青岛将建成全球知名的海湾都会",
    likeNum: 1722,
    commentNum: 22,
    likeState: true,
  },
  {
    id: 2,
    vUrl: "http://qn.ifakq.com/t2.mp4",
    title: "Samsonnnnn",
    desc: "一个流汗黄豆，融合了多少网友的负面情感？",
    likeNum: 35663,
    commentNum: 202,
    likeState: true,
  },
  {
    id: 3,
    vUrl: "http://qn.ifakq.com/t3.mp4",
    title: "Samson",
    desc: "公示！到2050年，青岛将建成全球知名的海湾都会",
    likeNum: 533,
    commentNum: 0,
    likeState: false,
  },
  {
    id: 4,
    vUrl: "http://qn.ifakq.com/t4.mp4",
    title: "Samson",
    desc: "公示！到2050年，青岛将建成全球知名的海湾都会",
    likeNum: 1735,
    commentNum: 11,
    likeState: true,
  },
  {
    id: 5,
    vUrl: "http://qn.ifakq.com/t5.mp4",
    title: "Samson",
    desc: "公示！到2050年，青岛将建成全球知名的海湾都会",
    likeNum: 128,
    commentNum: 5,
    likeState: false,
  },
  {
    id: 6,
    vUrl: "http://qn.ifakq.com/t6.mp4",
    title: "Samson",
    desc: "公示！到2050年，青岛将建成全球知名的海湾都会",
    likeNum: 7798,
    commentNum: 50,
    likeState: false,
  },
  {
    id: 7,
    vUrl: "http://qn.ifakq.com/t7.mp4",
    title: "Samson",
    desc: "公示！到2050年，青岛将建成全球知名的海湾都会",
    likeNum: 987123,
    commentNum: 8001,
    likeState: false,
  },
  {
    id: 8,
    vUrl: "http://qn.ifakq.com/t8.mp4",
    title: "Samson",
    desc: "公示！到2050年，青岛将建成全球知名的海湾都会",
    likeNum: 735,
    commentNum: 2,
    likeState: true,
  },
  {
    id: 9,
    vUrl: "http://qn.ifakq.com/t9.mp4",
    title: "Samson",
    desc: "公示！到2050年，青岛将建成全球知名的海湾都会",
    likeNum: 57777,
    commentNum: 6666,
    likeState: true,
  },
  {
    id: 10,
    vUrl: "http://qn.ifakq.com/t10.mp4",
    title: "Samson",
    desc: "公示！到2050年，青岛将建成全球知名的海湾都会",
    likeNum: 1923501,
    commentNum: 35001,
    likeState: false,
  },
  {
    id: 11,
    vUrl: "http://qn.ifakq.com/t11.mp4",
    title: "Samson",
    desc: "公示！到2050年，青岛将建成全球知名的海湾都会",
    likeNum: 13722,
    commentNum: 212,
    likeState: false,
  },
  {
    id: 12,
    vUrl: "http://qn.ifakq.com/t12.mp4",
    title: "Samson",
    desc: "公示！到2050年，青岛将建成全球知名的海湾都会",
    likeNum: 22,
    commentNum: 0,
    likeState: false,
  },
  {
    id: 13,
    vUrl: "http://qn.ifakq.com/t13.mp4",
    title: "Samson",
    desc: "公示！到2050年，青岛将建成全球知名的海湾都会",
    likeNum: 59,
    commentNum: 7,
    likeState: false,
  },
  {
    id: 14,
    vUrl: "http://qn.ifakq.com/t14.mp4",
    title: "Samson",
    desc: "公示！到2050年，青岛将建成全球知名的海湾都会",
    likeNum: 85512,
    commentNum: 987,
    likeState: false,
  },
  {
    id: 15,
    vUrl: "http://qn.ifakq.com/t15.mp4",
    title: "Samson",
    desc: "公示！到2050年，青岛将建成全球知名的海湾都会",
    likeNum: 1722,
    commentNum: 22,
    likeState: false,
  },
  {
    id: 16,
    vUrl: "http://qn.ifakq.com/t16.mp4",
    title: "Samson",
    desc: "公示！到2050年，青岛将建成全球知名的海湾都会",
    likeNum: 53142,
    commentNum: 11123,
    likeState: false,
  },
  {
    id: 17,
    vUrl: "http://qn.ifakq.com/t17.mp4",
    title: "Samson",
    desc: "公示！到2050年，青岛将建成全球知名的海湾都会",
    likeNum: 777777,
    commentNum: 12351,
    likeState: false,
  },
  {
    id: 18,
    vUrl: "http://qn.ifakq.com/t18.mp4",
    title: "Samson",
    desc: "公示！到2050年，青岛将建成全球知名的海湾都会",
    likeNum: 531211,
    commentNum: 54512,
    likeState: false,
  },
  {
    id: 19,
    vUrl: "http://qn.ifakq.com/t19.mp4",
    title: "Samson",
    desc: "公示！到2050年，青岛将建成全球知名的海湾都会",
    likeNum: 781412,
    commentNum: 5321,
    likeState: false,
  },
  {
    id: 20,
    vUrl: "http://qn.ifakq.com/t20.mp4",
    title: "Samson",
    desc: "公示！到2050年，青岛将建成全球知名的海湾都会",
    likeNum: 98441,
    commentNum: 9012,
    likeState: false,
  },
];
const pageScore = 10;
export const homeList = (pageNum: number) => {
  let callBackArry = list.slice((pageNum - 1) * pageScore, pageNum * pageScore);
  return {
    data: callBackArry,
    code: 200,
  };
};
