const list = [
  {
    id: 1,
    vUrl: "https://v-cdn.zjol.com.cn/280443.mp4",
    title: "Samson",
    desc: "测试测试视频11阿斯蒂芬阿斯顿法定",
    likeNum: 1722,
    commentNum: 22,
    likeState: true,
  },
  {
    id: 2,
    vUrl: "https://v-cdn.zjol.com.cn/276982.mp4",
    title: "Samsonnnnn",
    desc: "以上来自于“浙视频”，更换视频名字就可以找到更多的视频了,",
    likeNum: 35663,
    commentNum: 202,
    likeState: true,
  },
  {
    id: 3,
    vUrl: "https://v-cdn.zjol.com.cn/276984.mp4",
    title: "Samson",
    desc: "以上来自于“浙视频”，更换视频名字就可以找到更多的视频了,",
    likeNum: 533,
    commentNum: 0,
    likeState: false,
  },
  {
    id: 4,
    vUrl: "https://v-cdn.zjol.com.cn/276985.mp4",
    title: "Samson",
    desc: "以上来自于“浙视频”，更换视频名字就可以找到更多的视频了,",
    likeNum: 1735,
    commentNum: 11,
    likeState: true,
  },
  {
    id: 5,
    vUrl: "https://v-cdn.zjol.com.cn/276986.mp4",
    title: "Samson",
    desc: "以上来自于“浙视频”，更换视频名字就可以找到更多的视频了,",
    likeNum: 128,
    commentNum: 5,
    likeState: false,
  },
  {
    id: 6,
    vUrl: "https://v-cdn.zjol.com.cn/276987.mp4",
    title: "Samson",
    desc: "以上来自于“浙视频”，更换视频名字就可以找到更多的视频了,",
    likeNum: 7798,
    commentNum: 50,
    likeState: false,
  },
  {
    id: 7,
    vUrl: "https://v-cdn.zjol.com.cn/276988.mp4",
    title: "Samson",
    desc: "以上来自于“浙视频”，更换视频名字就可以找到更多的视频了,",
    likeNum: 987123,
    commentNum: 8001,
    likeState: false,
  },
  {
    id: 8,
    vUrl: "https://v-cdn.zjol.com.cn/276989.mp4",
    title: "Samson",
    desc: "以上来自于“浙视频”，更换视频名字就可以找到更多的视频了,",
    likeNum: 735,
    commentNum: 2,
    likeState: true,
  },
  {
    id: 9,
    vUrl: "https://v-cdn.zjol.com.cn/276990.mp4",
    title: "Samson",
    desc: "以上来自于“浙视频”，更换视频名字就可以找到更多的视频了,",
    likeNum: 57777,
    commentNum: 6666,
    likeState: true,
  },
  {
    id: 10,
    vUrl: "https://v-cdn.zjol.com.cn/276991.mp4",
    title: "Samson",
    desc: "以上来自于“浙视频”，更换视频名字就可以找到更多的视频了,",
    likeNum: 1923501,
    commentNum: 35001,
    likeState: false,
  },
  {
    id: 11,
    vUrl: "https://v-cdn.zjol.com.cn/276992.mp4",
    title: "Samson",
    desc: "以上来自于“浙视频”，更换视频名字就可以找到更多的视频了,",
    likeNum: 13722,
    commentNum: 212,
    likeState: false,
  },
  {
    id: 12,
    vUrl: "https://v-cdn.zjol.com.cn/276993.mp4",
    title: "Samson",
    desc: "以上来自于“浙视频”，更换视频名字就可以找到更多的视频了,",
    likeNum: 22,
    commentNum: 0,
    likeState: false,
  },
  {
    id: 13,
    vUrl: "https://v-cdn.zjol.com.cn/276994.mp4",
    title: "Samson",
    desc: "以上来自于“浙视频”，更换视频名字就可以找到更多的视频了,",
    likeNum: 59,
    commentNum: 7,
    likeState: false,
  },
  {
    id: 14,
    vUrl: "https://v-cdn.zjol.com.cn/276996.mp4",
    title: "Samson",
    desc: "以上来自于“浙视频”，更换视频名字就可以找到更多的视频了,",
    likeNum: 85512,
    commentNum: 987,
    likeState: false,
  },
  {
    id: 15,
    vUrl: "https://v-cdn.zjol.com.cn/276998.mp4",
    title: "Samson",
    desc: "以上来自于“浙视频”，更换视频名字就可以找到更多的视频了,",
    likeNum: 1722,
    commentNum: 22,
    likeState: false,
  },
  {
    id: 16,
    vUrl: "https://v-cdn.zjol.com.cn/277000.mp4",
    title: "Samson",
    desc: "以上来自于“浙视频”，更换视频名字就可以找到更多的视频了,",
    likeNum: 53142,
    commentNum: 11123,
    likeState: false,
  },
  {
    id: 17,
    vUrl: "https://v-cdn.zjol.com.cn/277001.mp4",
    title: "Samson",
    desc: "以上来自于“浙视频”，更换视频名字就可以找到更多的视频了,",
    likeNum: 777777,
    commentNum: 12351,
    likeState: false,
  },
  {
    id: 18,
    vUrl: "https://v-cdn.zjol.com.cn/277002.mp4",
    title: "Samson",
    desc: "以上来自于“浙视频”，更换视频名字就可以找到更多的视频了,",
    likeNum: 531211,
    commentNum: 54512,
    likeState: false,
  },
  {
    id: 19,
    vUrl: "https://v-cdn.zjol.com.cn/277003.mp4",
    title: "Samson",
    desc: "以上来自于“浙视频”，更换视频名字就可以找到更多的视频了,",
    likeNum: 781412,
    commentNum: 5321,
    likeState: false,
  },
  {
    id: 20,
    vUrl: "https://v-cdn.zjol.com.cn/277004.mp4",
    title: "Samson",
    desc: "以上来自于“浙视频”，更换视频名字就可以找到更多的视频了,",
    likeNum: 98441,
    commentNum: 9012,
    likeState: false,
  },
];
const pageScore = 10;
export const homeList = (pageNum: number) => {
  let callBackArry = list.slice((pageNum - 1) * pageScore, pageNum * pageScore);
  return {
    data: callBackArry,
    code: 200,
  };
};
